CREATE TYPE TIPO_ESTADO AS ENUM ('COMPLETO', 'EM DESENVOLVIMENTO', 'NÃO INICIADO');

CREATE TABLE DESENVOLVEDOR(
    NOME   VARCHAR(30)      NOT NULL,
    EMAIL  VARCHAR(30)      NOT NULL,
    SENHA  VARCHAR(30)      NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE PROJETO(
    ID          INTEGER      PRIMARY KEY,
    NOME        VARCHAR(30) NOT NULL,
    DATACRIACAO VARCHAR(30) NOT NULL,
    ESTADO      TIPO_ESTADO NOT NULL,
    ADMEMAIL    VARCHAR(30) NOT NULL,
    FOREIGN KEY (ADMEMAIL)  REFERENCES DESENVOLVEDOR(EMAIL)
);

CREATE TABLE CRONOGRAMA(
    PID         INTEGER     NOT NULL,
    FOREIGN KEY (PID)       REFERENCES PROJETO(ID),
    PRIMARY KEY (PID)
);

CREATE TABLE ATIVIDADE(
    ID          INTEGER      PRIMARY KEY,
    NOME        VARCHAR(30) NOT NULL, 
    DATACRIACAO DATE,
    DATATERMINO DATE        NOT NULL,
    ESTADO      TIPO_ESTADO NOT NULL,
    DESCRICAO   VARCHAR(100),
    PID         INTEGER     NOT NULL,
    FOREIGN KEY (PID)       REFERENCES PROJETO(ID),
    FOREIGN KEY (PID)       REFERENCES CRONOGRAMA(PID)
);

CREATE TABLE EXECUTA(
    DEVEMAIL    VARCHAR(30) NOT NULL,
    ATVID       INTEGER     NOT NULL,
    FOREIGN KEY (DEVEMAIL)  REFERENCES DESENVOLVEDOR(EMAIL),
    FOREIGN KEY (ATVID)     REFERENCES ATIVIDADE(ID),
    PRIMARY KEY (DEVEMAIL, ATVID)
);

CREATE TABLE PARTICIPA(
    DEVEMAIL    VARCHAR(30) NOT NULL,
    PID         INTEGER     NOT NULL,
    FOREIGN KEY (DEVEMAIL)  REFERENCES DESENVOLVEDOR(EMAIL),
    FOREIGN KEY (PID)       REFERENCES PROJETO(ID),
    PRIMARY KEY (DEVEMAIL, PID)
);

CREATE TABLE FORUM(
    PID         INTEGER NOT NULL,
    FOREIGN KEY (PID)   REFERENCES PROJETO(ID),
    PRIMARY KEY (PID)
);

CREATE TABLE TOPICO(
    ID          INTEGER      PRIMARY KEY,
    DATACRIACAO DATE         NOT NULL,
    TITULO      VARCHAR(150) NOT NULL,
    FORID       INTEGER      NOT NULL,
    AUTEMAIL    VARCHAR(30)  NOT NULL,
    FOREIGN KEY (FORID)      REFERENCES FORUM(PID),
    FOREIGN KEY (AUTEMAIL)   REFERENCES DESENVOLVEDOR(EMAIL)
);

CREATE TABLE MENSAGEM(
    ID          INTEGER      PRIMARY KEY,
    DATACRIACAO DATE         NOT NULL,
    TEXTO       VARCHAR(300) NOT NULL,
    TOPID       INTEGER      NOT NULL,
    AUTEMAIL    VARCHAR(30)  NOT NULL,
    FOREIGN KEY (TOPID)      REFERENCES TOPICO(ID),
    FOREIGN KEY (AUTEMAIL)   REFERENCES DESENVOLVEDOR(EMAIL)
);