# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
    ]
